repos:
  - repo: https://github.com/semgrep/pre-commit
    rev: v1.122.0
    hooks:
      - id: semgrep
        name: semgrep - Security Rules
        entry: semgrep
        args:
          [
            "--config=p/r2c-security-audit",   # General security audits
            "--config=p/owasp-top-ten",        # OWASP Top 10 security issues
            "--config=p/secrets",              # Hardcoded secrets detection
            "--config=p/dockerfile",           # Dockerfile issues
            "--config=p/golang",               # Go security rules
            "--config=p/python",               # Python security rules
            "--config=p/java",                 # Java security rules
            "--config=p/typescript"            # TypeScript rules
          ]
