repos:
  - repo: https://github.com/semgrep/pre-commit
    rev: v1.122.0
    hooks:
      - id: semgrep
        entry: semgrep
        #Replace <SEMGREP_RULESET_URL> with your custom rule source
        #or see https://semgrep.dev/explore to select a ruleset and copy its URL
        args: ['--config','p/gitleaks','--config', 'p/secrets','--config', 'p/comment','--config','p/cwe-top-25', '--error', '--skip-unknown-extensions']