repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.122.0  # Replace with latest stable Semgrep CLI release
    hooks:
      - id: semgrep
        args: ["--config=https://semgrep.dev/p/java"]  # You can use "--config=YOUR_URL" for custom rules

