repos:
  - repo: local
    hooks:
      - id: semgrep-warn-only
        name: Semgrep (Warn Only)
        entry: bash ./semgrep-warn-only.sh
        language: system
        pass_filenames: false
        verbose: false