repos:
  - repo: https://github.com/returntocorp/semgrep
    rev: v1.119.0  # You can update this to the latest Semgrep release
    hooks:
      - id: semgrep
        name: semgrep - All Major Security Rules
        args:
          [
            "--config=p/r2c-security-audit",  # Comprehensive security audit rules
            "--config=p/owasp-top-ten",           # OWASP Top 10 rules
            "--config=p/secrets",                 # Secrets detection
            "--config=p/dockerfile",              # Dockerfile-specific security
            "--config=p/golang",                  # Go security
            "--config=p/python",                  # Python security
            "--config=p/javascript",              # JavaScript security
            "--config=p/typescript",              # TypeScript security
          ]
